### ISSUE TITLE
The Dart protoc plug-in is not supported on Windows

### ISSUE THREAD

**Issue by unicomp21** [dart-lang/dart-protoc-plugin#10]
lots of errors in the latest dart editor, also, can this be built on Windows? or just Linux?

**Comment by dss539** [comment]
It appears the only thing hindering Windows support is that one bash script.
You can work around this by creating a file named `protoc-gen-dart.bat` alongside the existing `protoc-gen-dart` shell script.
Inside the bat file, add this content...

```
@echo off
pushd %~dp0
set BINDIR=%CD%
popd
dart "%BINDIR%\protoc_plugin.dart" -c "%*"
```

When you invoke protoc, use these args:

`protoc ^^my_message.proto^^ --plugin=protoc-gen-dart=^^C:\dart-protoc-plugin\bin^^\protoc-gen-dart.bat --dart_out=.`

_replace sections enclosed by ^^ with your own filename/path_

**Comment by sigurdm** [comment]
After https://github.com/protocolbuffers/protobuf/pull/5105 has come into a release you should be able to `pub global activate protoc_plugin`, add the pub cache to your path and run `protoc --dart_out=...`.

**Comment by letmefly** [comment]
please support windows platform, ths

**Comment by sigurdm** [comment]
@letmefly could you elaborate on what you are trying, what versions you are using and what goes wrong?
Windows should be supported now.

I have just tried out the combination of  protoc-3.7.1, dart 2.2.0 and protoc_plugin v. 16.0.1 on  windows-server-2016.
I installed dart protoc_plugin with:
```
pub global activate protoc_plugin
```
Make sure C:\Users\<username>\AppData\Roaming\Pub\Cache\bin is in your %path.

And ran:
```
protoc-3.7.1-win64\bin\protoc.exe --dart_out=. -Iprotos test.proto
```
And everything seemed to work.
