### ISSUE TITLE
Dart 2 runtime failures in tests

### ISSUE THREAD

**Issue by keertip** [dart-lang/dart-protoc-plugin#105]
When running tests in dart 2 mode,

00:03 +55 -1: testDefaultMessageIsReadOnly [E]                                                                                                                                                         
  Expected: throws UnsupportedError
    Actual: <Closure: () => Null>
     Which: threw ?:<type 'String' is not a subtype of type 'Null' of 'value' where
                    String is from dart:core
                    Null is from dart:core
                  >
            stack dart:_internal                                                                            UnmodifiableListBase.add
                  ../../protoc_plugin/test/generated_message_test.dart 94:30  main.<fn>.<fn>

 type '(TestAllTypes_NestedMessage) => void' is not a subtype of type '(dynamic) => void'
  ../..//protoc_plugin/test/repeated_field_test.dart 50:54  main.<fn>

 type 'Future<GeneratedMessage>' is not a subtype of type 'Future<SearchResponse>' where
    Future is from dart:async
    GeneratedMessage is from package:protobuf/protobuf.dart
    Future is from dart:async
    SearchResponse is from package:protoc_plugin/test/protos/service.pb.dart
  
  package:protoc_plugin/test/protos/service.pb.dart 77:20                         SearchServiceApi.search
  ../../tmp/archives/third_party/dart/protoc_plugin/test/service_test.dart 81:27  main.<fn>

and more....

**Comment by jakobr-google** [comment]
Fixed in #106.
