### ISSUE TITLE
Can't use with Flutter.

### ISSUE THREAD

**Issue by tonikami** [dart-lang/dart-protoc-plugin#117]
When I run pub install 

**The current Dart SDK version is 2.0.0-dev.69.5.flutter-eab492385c.

Because protoc_plugin requires SDK version >=2.0.0 <3.0.0, version solving failed.**

I have the latest flutter SDK.
I think the changes made 7 days ago makes this no longer work with flutter.

**Comment by zoechi** [comment]
Use an older protobuf version that is compatible with 2.0.0-dev.96.5 until Flutter is available with Dart 2.0.0 final.

**Comment by sigurdm** [comment]
The flutter master channel is already fully on dart 2 and should work with the newest protoc.
To try it out you can run
```
flutter channel master
```
(If you encounter problems with this you can go back with `flutter channel beta`)

The next flutter beta release will also be on dart 2 and should be released before too long.
