### ISSUE TITLE
native representation for some scalar value types?

### ISSUE THREAD

**Issue by mmaz** [dart-lang/dart-protoc-plugin#13]
Are there any protobuf scalar value types for which dart-protoc generates `num` or `int` getters (either by default, or requested as an option to `--dart-out`)? The default type `ByteData` has convenience methods, such as `getInt32()`, but since some types in the protocol buffer spec are always stored as little-endian (such as `fixed64` and `fixed32`), perhaps these protobuf types could be automatically lifted to Dart-native primitives inside of the generated code itself. 

My apologies if this has been proposed and rejected already (or proposed and blocking on dart2js's open issue regarding 64-bit conversions).

**Comment by jakobr-google** [comment]
Sounds like this has already been fixed. If you disagree, please reopen this issue and add a comment.
