### ISSUE TITLE
Warnings for unused imports

### ISSUE THREAD

**Issue by Fox32** [dart-lang/dart-protoc-plugin#15]
For my project, every file that was generated by to protoc plugin contains a import of typed_data, but is not using it. The dart editor issues a warning for every file.

If the import is never used it should probably be removed. But if it is used only in some situations, it should be only added then.
This is more a small flaw, but I try to have no warnings in my project.

**Comment by skybrian** [comment]
The issue with unused fixnum imports will be fixed with this patch:
https://chromiumcodereview.appspot.com/1274813003/patch/1/10005

I don't think we're generating any typed_data imports anymore.

**Comment by skybrian** [comment]
Fixed in 0.4.1.
