### ISSUE TITLE
Import paths in generated files

### ISSUE THREAD

**Issue by tcriess** [dart-lang/dart-protoc-plugin#16]
When using "import" in the .proto file, the generated dart file seems to use a wrong path in the corresponding import statement.
Example:
/a/aa/aaa/aaaa.proto
/a/bb/bbb.proto

aaaa.proto:

```
package a.aa.aaa;
import "a/bb/bbb.proto";
message AAAA {
        required a.bb.BBB bbb = 1;
}
```

bbb.proto:

```
package a.bb;
message BBB {
        required string id = 1;
}
```

Running protoc like (from /)

```
protoc --dart_out=./ a/aa/aaa/aaaa.proto
```

Then the resulting /a/aa/aaa/aaaa.pb.dart contains an import statement

```
import 'bb/bbb.pb.dart';
```

Shouldn't that be '../../bb/bbb.pb.dart'?

**Comment by sigurdm** [comment]
This seems to not reproduce anymore on master. I get `import '../../bb/bbb.pb.dart' as $a$bb;` please reopen if this is still an issue.
