### ISSUE TITLE
is there any plans to integrate this plugin upstream?

### ISSUE THREAD

**Issue by lsching17** [dart-lang/dart-protoc-plugin#27]
is there any plans to integrate the logic of this plugin into upstream protoc compiler? This free user from the burden to compile "out/protoc-gen-dart" and can support Windows plalform easily.

**Comment by skybrian** [comment]
I don't know of any plans to do that. It seems like it would complicate the release process, since we'd have to do a protoc release to change something in the Dart plugin, and people would have to install a new version of protoc.

**Comment by sigurdm** [comment]
This plugin can now be installed with `pub global activate protoc_plugin` even on windows when the .bat file support lands.
I don't think it is in our current plans to integrate this into protoc itself.
