### ISSUE TITLE
Add support installing via pub global activate

### ISSUE THREAD

**Issue by Fox32** [dart-lang/dart-protoc-plugin#33]
I think it should not be diffcult to install and use the package via [`pub global activate`](https://www.dartlang.org/tools/pub/cmd/pub-global.html). I couldn't test it yet as I only have a Windows system, but this small change should make is possible:

https://github.com/Fox32/dart-protoc-plugin/commit/5f40ad2db29d3bc58812b9ff9efb7c77b7c028da

It would also require to publish it to pub. But this would make installing much easier for most people. Due to snapshots I would also expect a much higher performance.

**Comment by Fox32** [comment]
I finally tested installing via pub global activate as described above and it seems to work fine! (on non Windows OS)

**Comment by kevmoo** [comment]
@skybrian Did you try this? It would greatly improve usability

**Comment by skybrian** [comment]
I haven't done anything about making open source usage easier. There are a bunch of other things to think about as well, like perhaps a transformer to find and call protoc and figuring out how to handle protobuf library upgrades smoothly.

**Comment by jakobr-google** [comment]
Fixed, thanks to @taisph. I've uploaded the package to pub as well, so now `pub global activate protoc_plugin` should do the trick.
