### ISSUE TITLE
Can't use pub install

### ISSUE THREAD

**Issue by hjfreyer** [dart-lang/dart-protoc-plugin#36]
The current pubspec depends on protobuf 0.3.5. That revision is present in github, but hasn't been pushed to https://pub.dartlang.org/packages/protobuf

**Comment by kevmoo** [comment]
Yup. I have a CL out to do some cleanup and I'll publish 0.3.5

**Comment by kevmoo** [comment]
Fixed!

https://pub.dartlang.org/packages/protobuf
