### ISSUE TITLE
Move continuous build to Travis

### ISSUE THREAD

**Issue by skybrian** [dart-lang/dart-protoc-plugin#40]

**Comment by kevmoo** [comment]
@skybrian I've been hacking at this 2 hours. I need to custom build protobuf 2.5 on travis to get it to work.

You owe me a cookie – if I figure it out. :confounded:

**Comment by kevmoo** [comment]
I like Chocolate Chip :smiling_imp:

**Comment by skybrian** [comment]
Thanks! I can take it from here if you'd rather do that.
