### ISSUE TITLE
avoid conflicts between top-level names in the protobuf library and message types

### ISSUE THREAD

**Issue by skybrian** [dart-lang/dart-protoc-plugin#47]
.pb.dart files should import "protobuf" using a prefix such as $pb, to avoid any possibility of name conflicts.

**Comment by sigurdm** [comment]
This is fixed by https://github.com/dart-lang/dart-protoc-plugin/pull/118

**Comment by nichite** [comment]
Now that #119 is merged, okay to close?

**Comment by sigurdm** [comment]
Yes! thanks
