### ISSUE TITLE
regenerate pb.dart whenever the protobuf library version in pubspec.yaml changes

### ISSUE THREAD

**Issue by skybrian** [dart-lang/dart-protoc-plugin#49]
The API between dart-protobuf and dart-protoc-plugin can change between versions. This is a problem if someone checks in a .pb.dart file.

It would be better to convert the .proto file into a JSON file, check in the JSON file, and run a transformer to generate the .pb.dart file. Then the .pb.dart file would always match the protobuf library.

If you change a .proto file, you still need to run protoc, though.

**Comment by skybrian** [comment]
Alternately, we could provide a way to bundle a private version of the protobuf library (vendoring), so that it doesn't conflict with the library's users.

**Comment by sigurdm** [comment]
I think this will be covered by https://github.com/dart-lang/dart-protoc-plugin/issues/99 . As I understand it, build runner automatically reruns when the pubspec dependencies have changed.
