### ISSUE TITLE
verify that package names are resolved properly

### ISSUE THREAD

**Issue by skybrian** [dart-lang/dart-protoc-plugin#50]
From the spec:

"Type name resolution in the protocol buffer language works like C++: first the innermost scope is searched, then the next-innermost, and so on, with each package considered to be "inner" to its parent package. A leading '.' (for example, .foo.bar.Baz) means to start from the outermost scope instead."

Perhaps these names are resolved before the Dart plugin sees them, but we should probably check the corner cases.

**Comment by sigurdm** [comment]
I don't think we have any reason to doubt what we get from protoc is resolved correctly. Please reopen if we have specific corner cases.
