### ISSUE TITLE
Add support for proto3

### ISSUE THREAD

**Issue by rwl** [dart-lang/dart-protoc-plugin#53]
If I process this definition:
```protobuf
syntax = "proto3";

message Point {
  int32 latitude = 1;
  int32 longitude = 2;
}
```
using this command:

    $ protoc --dart_out=. point.proto

I get this error:

    point.proto:1:10: Unrecognized syntax identifier "proto3".  This parser only recognizes "proto2".

**Comment by rwl** [comment]
It turns out that if you install [Protocol Buffers v3](https://github.com/google/protobuf/releases), like a sensible person, then it compiles the definition just fine.

I suppose the question is then, does the [runtime library](https://github.com/dart-lang/dart-protobuf) support `proto3`?

**Comment by skybrian** [comment]
There's no explicit support for proto3 features such as maps yet, but they are wire-compatible with proto2, so you might still be able to work with them using the old representation.
