### ISSUE TITLE
can't build protoc-gen-dart using Dart 1.18

### ISSUE THREAD

**Issue by skybrian** [dart-lang/dart-protoc-plugin#58]
protoc is still using dart2dart and this seems to have broken with Dart 1.18. The error is:

'file:///usr/local/google/home/skybrian/dart/work/dart-protoc-plugin/out/protoc-gen-dart': error: line 2617 pos 18: unresolved reference to instance field 'name_A'
  FieldInfo(this.name_A, this.tagNumber, this.index_A, int type_A, [dynamic defaultOrMaker, this.subBuilder, this.valueOf_D]) : this.type = type_A, this.makeDefault = findMakeDefault(type_A, defaultOrMaker), this.check = null {

It's not worth fixing dart2dart since it will go away soon. We should switch to a different way of building it. 

For now, a workaround is to use Dart 1.17 for rebuilding protoc-gen-dart.

**Comment by skybrian** [comment]
https://codereview.chromium.org/2107023003/

**Comment by kevmoo** [comment]
Closed by c6b927d8b882d5a913f8fa36e62ecf6ec1435913 – I think?
