### ISSUE TITLE
make build-plugin error on 1.19.1

### ISSUE THREAD

**Issue by czlbaiyi** [dart-lang/dart-protoc-plugin#62]
➜  dart-protoc-plugin-0.5.1 make build-plugin
[ -d out ] || mkdir out
# --categories=all is a hack, it should be --categories=Server once dart2dart bug is fixed.
dart2js --checked --output-type=dart --show-package-warnings --categories=all -oout/protoc-gen-dart bin/protoc_plugin.dart
Usage: dart2js [options] dartfile

Compiles Dart to JavaScript.

Common options:
  -o <file> Generate the output into <file>.
  -c        Insert runtime type checks and enable assertions (checked mode).
  -m        Generate minified output.
  -h        Display this message (add -v for information about all options).

Error: --output-type=dart is no longer supported. It was deprecated since Dart 1.11 and removed in Dart 1.19.
make: *** [out/protoc-gen-dart] Error 1
➜  dart-protoc-plugin-0.5.1 dart --version
Dart VM version: 1.19.1 (Wed Sep  7 08:59:17 2016) on "macos_x64"

**Comment by skybrian** [comment]
I think this should be fixed on trunk. (The commit is "stop using dart2dart in Makefile".)

https://github.com/dart-lang/dart-protoc-plugin/commit/c6b927d8b882d5a913f8fa36e62ecf6ec1435913

**Comment by czlbaiyi** [comment]
@skybrian, sorry for this ,i am use the release version. its my fault
