### ISSUE TITLE
out/protoc-gen-dart not being generated

### ISSUE THREAD

**Issue by ehrt74** [dart-lang/dart-protoc-plugin#63]
Hi!

Maybe I'm doing something stupid here, but I've cloned the source code and when I run "make build-plugin" the message comes "nothing to do for build-plugin" and the folder "out/" is not created. 

Has something changed with the build/install process?

Many thanks :)

**Comment by czlbaiyi** [comment]
Maybe you  shoud pub install first

**Comment by ehrt74** [comment]
Yes, I did that first. 

No folder called "out" is created.

**Comment by skybrian** [comment]
The README is out of date, and the Makefile could be cleaned up too.

bin/protoc-gen-dart is a checked-in shell script now, so we don't really need the 'build-plugin' target anymore.

I usually run "make run-tests". This should build everything and run the tests. If all the tests pass then things are basically working. But, that doesn't help you integrate it into your build.

The shell script could also use some work; I think right now it only works if you are in the dart-protoc-plugin directory. It should be modified to work from a different current directory, so you can add it to your PATH.

**Comment by skybrian** [comment]
(Ideally we could use "pub global activate" to install it, but I'm not sure what's involved.)

**Comment by MikeMitterer** [comment]
If someone else finds this:
What I did: (on Mac)

- brew install protobuf260
- git clone https://github.com/dart-lang/dart-protoc-plugin.git
- cd dart-protoc-plugin
- pub update
- make run-tests

cd to out
You should see the generated protos!

**Comment by jakobr-google** [comment]
@unicomp21 are you referring to this specific issue, or something else? The issue here is that the documentation is out of date, but what @MikeMitterer wrote should work fine.

And yes, this is used heavily internally. The actual code is up to date with the internal version, but the tooling, and especially the documentation here, needs some work. Your PRs are most welcome!
