### ISSUE TITLE
name conflict between message name and generated class for extensions

### ISSUE THREAD

**Issue by skybrian** [dart-lang/dart-protoc-plugin#67]
If you have a file named foo.proto and it contains a message named Foo, and it also defines extensions, the plugin we will generate two Dart classes with the same name (both Foo).

See: https://github.com/dart-lang/dart-protoc-plugin/blob/master/lib/file_generator.dart#L211

We should automatically rename the extension class when there's a conflict, or better yet eliminate it as the TODO suggests (but that would require a migration.)

**Comment by jakobr-google** [comment]
Fixed in #70. Extension class is renamed if there is a conflict.
