### ISSUE TITLE
protoc-gen-dart does not work on mac.

### ISSUE THREAD

**Issue by jonahwilliams** [dart-lang/dart-protoc-plugin#77]
I dowloaded and tried to run protoc with the latest version of the dart plugin, but it fails with the message below.

```
Unhandled exception:
Could not load "file:///Users/**/depot/protoc_plugin.dart": FileSystemException: Cannot open file, path = '/Users/***/depot/protoc_plugin.dart' (OS Error: No such file or directory, errno = 2)
null
--dart_out: protoc-gen-dart: Plugin failed with status code 255.
```

The problem is in the bin/protoc-gen-dart script.  From what I can tell,`readlink -f` is not supported on mac.  If I remove this line and replace it with something like a hardcoded path or `BINDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"`  (thanks StackOverflow), then the plugin works perfectly.

**Comment by jakobr-google** [comment]
Thanks for reporting this! I couldn't find a good way to fix it that works in all cases (when `protoc-gen-dart` on PATH is a symlink to `.../bin/protoc-gen-dart`), so I'll just remove the use of readlink, and not support symlinks.

The best way to run the plugin is using `pub global activate protoc_plugin` (and adding `~/.pub-cache/bin` to your PATH), which should work fine on macOS. Alternatively, you can pass the path to the plugin on the protoc command line:

    protoc --dart_out=out --plugin=protoc-gen-dart=<.../dart-protoc-plugin/bin/protoc-gen-dart> ...
